//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvanceDiarioOperarios
    {
        public int idPromocion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string idTurno { get; set; }
        public string idMesa { get; set; }
        public string Legajo { get; set; }
    
        public virtual EmpresasOperario EmpresasOperario { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual Promocione Promocione { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
