//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CopackerEntities : DbContext
    {
        public CopackerEntities()
            : base("name=CopackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DotacionSolicitada> DotacionSolicitadas { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<EmpresasOperario> EmpresasOperarios { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<MotivosHorasPerdida> MotivosHorasPerdidas { get; set; }
        public virtual DbSet<Turno> Turnos { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedidas { get; set; }
        public virtual DbSet<AvanceDiario> AvanceDiarios { get; set; }
        public virtual DbSet<AvanceDiarioOperarios> AvanceDiarioOperarios1 { get; set; }
        public virtual DbSet<FormulasKit> FormulasKits { get; set; }
        public virtual DbSet<InsumosProducto> InsumosProductos { get; set; }
        public virtual DbSet<Kits> Kits1 { get; set; }
        public virtual DbSet<Perfiles> Perfiles1 { get; set; }
        public virtual DbSet<Promocione> Promociones { get; set; }
        public virtual DbSet<PromocionesEmpresas> PromocionesEmpresas1 { get; set; }
        public virtual DbSet<StockAjustes> StockAjustes1 { get; set; }
        public virtual DbSet<StockAjustesMotivo> StockAjustesMotivos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoKit> TipoKits { get; set; }
        public virtual DbSet<Usuarios> Usuarios1 { get; set; }
    }
}
