//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kits
    {
        public string idKit { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public string idTipoKit { get; set; }
        public Nullable<decimal> CantKit { get; set; }
        public Nullable<bool> EstaActivo { get; set; }
        public Nullable<decimal> PorcentajeMermaPermitido { get; set; }
        public Nullable<decimal> CostoxHoraCliente { get; set; }
        public string idUniMed { get; set; }
        public Nullable<decimal> Palletizado { get; set; }
        public string idUsuarioUltimaModificacion { get; set; }
    
        public virtual TipoKit TipoKit { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual Usuarios Usuario { get; set; }
    }
}
