//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionesEmpresas
    {
        public int idPromocion { get; set; }
        public string idEmpresa { get; set; }
        public Nullable<decimal> CostoEmpresaxHora { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Promocione Promociones { get; set; }
    }
}
