//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promocione()
        {
            this.AvanceDiarios = new HashSet<AvanceDiario>();
            this.AvanceDiarioOperarios = new HashSet<AvanceDiarioOperarios>();
            this.PromocionesEmpresas = new HashSet<PromocionesEmpresas>();
        }
    
        public int idPromocion { get; set; }
        public string idKit { get; set; }
        public Nullable<int> EstadoPromocion { get; set; }
        public string DescripcionLargaKit { get; set; }
        public string DescripcionPromocion { get; set; }
        public string idPromocionCliente { get; set; }
        public string NroOrdenDeCompraInterna { get; set; }
        public Nullable<System.DateTime> FechaOrdenDeCompraInterna { get; set; }
        public string NroOrdenDeCompraCliente { get; set; }
        public Nullable<System.DateTime> FechaOrdenDeCompraCliente { get; set; }
        public Nullable<System.DateTime> FechaCreacionPromocion { get; set; }
        public Nullable<System.DateTime> FechaCierreAcordadoPromocion { get; set; }
        public Nullable<System.DateTime> FechaCierreRealPromocion { get; set; }
        public Nullable<decimal> PorcentajeMermaReal { get; set; }
        public Nullable<decimal> ProductividadEstandar { get; set; }
        public Nullable<decimal> CantKitsAProducir { get; set; }
        public Nullable<decimal> CostoClientexUnidad { get; set; }
        public string idUsuarioUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvanceDiario> AvanceDiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvanceDiarioOperarios> AvanceDiarioOperarios { get; set; }
        public virtual Usuarios Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromocionesEmpresas> PromocionesEmpresas { get; set; }
    }
}
