//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copacker
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAjustes
    {
        public int idAjuste { get; set; }
        public string idUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> CantAjustada { get; set; }
        public Nullable<bool> TipoAjuste { get; set; }
        public string idMotivo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual InsumosProducto InsumosProducto { get; set; }
        public virtual StockAjustesMotivo StockAjustesMotivo { get; set; }
        public virtual Usuarios Usuario { get; set; }
    }
}
